awk '
/Recent Files Horizontal Scroll/ {
    print "        // Storage & Sync Widget"
    print "        com.example.ui.components.GlassCard("
    print "            modifier = Modifier.fillMaxWidth(),"
    print "            shape = RoundedCornerShape(20.dp),"
    print "            backgroundColor = MaterialTheme.colorScheme.surfaceContainerHigh.copy(alpha = 0.5f),"
    print "            borderColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.15f),"
    print "            borderWidth = 1.dp"
    print "        ) {"
    print "            Row("
    print "                modifier = Modifier"
    print "                    .fillMaxWidth()"
    print "                    .padding(20.dp),"
    print "                horizontalArrangement = Arrangement.SpaceBetween,"
    print "                verticalAlignment = Alignment.CenterVertically"
    print "            ) {"
    print "                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(16.dp)) {"
    print "                    Box("
    print "                        modifier = Modifier.size(48.dp).clip(CircleShape).background(MaterialTheme.colorScheme.primary.copy(alpha=0.15f)),"
    print "                        contentAlignment = Alignment.Center"
    print "                    ) {"
    print "                        Icon(imageVector = Icons.Default.Description, contentDescription = null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(24.dp))"
    print "                    }"
    print "                    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {"
    print "                        Text(text = \"Local Storage\", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.ExtraBold, color = MaterialTheme.colorScheme.onSurface)"
    print "                        Text(text = \"1.2 GB used • 8.8 GB free\", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)"
    print "                    }"
    print "                }"
    print "                Box(modifier = Modifier.clip(RoundedCornerShape(9999.dp)).background(MaterialTheme.colorScheme.primary).padding(horizontal = 12.dp, vertical = 6.dp)) {"
    print "                    Text(text = \"Manage\", style = MaterialTheme.typography.labelSmall, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onPrimary)"
    print "                }"
    print "            }"
    print "        }"
    print ""
    print "        // Recent Files Horizontal Scroll"
    next
}
{ print }
' app/src/main/java/com/example/ui/screens/WorkspaceScreen.kt > tmp.kt && mv tmp.kt app/src/main/java/com/example/ui/screens/WorkspaceScreen.kt
